### ISSUE TITLE
Load rate structure from a file

### ISSUE THREAD

**Issue by christophertull** [California-Data-Collaborative/RateComparison#12]
Users should be able to load a rate structure from a file, either to set the baseline rates or to populate the boxes in the customer class tabs. There should probably be an import button somewhere.

Before this can happen, a format for storing and transmitting rates needs to be devised, which is a problem that I a working on, probably in a different repo.

**Comment by patwater** [comment]
Is the idea here that this hard coded global.R file would get pruned down (https://github.com/California-Data-Collaborative/rate-comparison/blob/master/global.R) and then instead the global.R would just pull in the right rate specification file according to the utility name provide: https://github.com/California-Data-Collaborative/Open-Water-Rate-Specification

Down the road if this truly was a standard one might not even need to have the open-water-rate-specification file on one's desktop... Just a well placed web hook or something like that :)

**Comment by christophertull** [comment]
Oooo, I like the webhook idea! And yeah, that is the general idea here. 

Re: issue #11 users should also be able to save a rate structure that they are in the process of designing so that they can come back and load it later.

**Comment by christophertull** [comment]
closed by #33
