### ISSUE TITLE
Change fixed charge based on meter size

### ISSUE THREAD

**Issue by christophertull** [California-Data-Collaborative/RateComparison#18]
The fixed charge should change based on the meter size of the account. There should be new input boxes on the left that allow the user to specify the charge for each meter size.

**Comment by christophertull** [comment]
Hey @monobina, any updates?

**Comment by monobina** [comment]
good timing @christophertull .. i have been planning to follow up with you on this. I have got this to work partially but not fully. I think your input will be very helpful as i might be missing something on how to incorporate this into the total bill info function

**Comment by monobina** [comment]
i am trying to insert a if else into the total bill calculation based on meter size but it only works for the first input and am not able to make it reactive for the rest.

**Comment by christophertull** [comment]
Hmm. If you push to a feature branch I could take a look.

**Comment by christophertull** [comment]
Or we could hop on a hangout if you would rather chat

**Comment by christophertull** [comment]
closed by #33
