### ISSUE TITLE
Change estimated water demand given price and price elasticity

### ISSUE THREAD

**Issue by christophertull** [California-Data-Collaborative/RateComparison#2]
Instead of assuming constant demand, water demand should change as price changes. These demand changes will then propagate down to revenue and equity considerations. This will depend on having estimates of price elasticity ( issue #1 ) 

If anyone has specific ideas about how this should be implemented, (i.e. someone with more economics knowledge than me!) please feel free to comment on this issue.

**Comment by christophertull** [comment]
If everything is planned correctly this issue could potentially be merged with issue #7 because an econometric model could be used both to forecast into the future and to account for price changes!

**Comment by EricSchles** [comment]
I'm going to hack on this!  Would it be possible to pair with someone on this? @christophertull

**Comment by christophertull** [comment]
Yeah definitely! By this weekend we will also have some public water meter data from the city of Santa Monica so the timing will be perfect for you to start playing around. When do you wanna chat @EricSchles ?

**Comment by patwater** [comment]
@EricSchles good sir!  Just wanted to circle back and see if you were still interested in hacking on this.  Would love to have your help on California's big drought!

**Comment by patwater** [comment]
Feel free to jump back in @EricSchles... will be just like this: https://www.youtube.com/watch?v=2WBG2rJZGW8

Actually in more ways than one with the DC and California relationship these days!

**Comment by christophertull** [comment]
Closed by #44

**Comment by patwater** [comment]
Cool very curious to see the final UI for how this price elasticity is incorporated
