### ISSUE TITLE
Show in graph when the real data ends and predictions start

### ISSUE THREAD

**Issue by christophertull** [California-Data-Collaborative/RateComparison#26]
Maybe add a vertical dotted line where the true data ends? or change to dashed line chart for predicted values?

**Comment by patwater** [comment]
I like the idea of a dashed line for predicted values though both would work.  If we're really smart we'll show error bars for the predicted values ;)

**Comment by anudeepvanjavakam1** [comment]
Hi Patrick,

Showing error bars is an excellent idea. I will try to work on it.

**Comment by christophertull** [comment]
Will take some thought about how we want to do error bars. Right now our forecasts are mean usage for each customer in each month. One option would be deriving error bars from the standard deviation of the residuals for each predicted month.

**Comment by patwater** [comment]
Yeah I think we might want to hold off on error bars while we're doing this sort of arithmetic accounting type forecast.  If we get into more sophisticated econometric type forecasting there's natural links to error bars with OLS and (I think?) also ARIMA.  

Might also be some stuff we can learn from the Water Demand Forecasting tool @fwhigh  and the DataKind folks built.  See here: https://github.com/California-Data-Collaborative/waterd/blob/master/app/train.R

Note also something we discussed with @EricSchles

**Comment by christophertull** [comment]
Going to close this for now. @anudeepvanjavakam1 added a nice looking line to demarcate the predictions:
![image](https://cloud.githubusercontent.com/assets/9061565/21239975/1996eb64-c2be-11e6-8005-cd756ad2d028.png)

Created a new issue for discussion of error bounds here: #31
