### ISSUE TITLE
Enabling planning with 0 months to forecast causes crash

### ISSUE THREAD

**Issue by christophertull** [California-Data-Collaborative/RateComparison#29]
To reproduce, set the number of months to forecast = 0 while planning is active.

Error:

> Warning in new_recent_month_data$usage_ccf[1:nrow(recent_month_data)] <- tmp$usage_ccf.y :
>   number of items to replace is not a multiple of replacement length
> Warning: Error in :: argument of length 0
> Stack trace (innermost first):
>     70: <reactive:planneddf> [C:\Users\Christopher\Documents\CA_Data_Collab\repos\RateComparison/server.R#71]
>     59: planneddf
>     58: dropNulls
>     57: updateSliderInput
>     56: observerFunc [C:\Users\Christopher\Documents\CA_Data_Collab\repos\RateComparison/server.R#204]
>      1: shiny::runApp
> Warning: Error in :: argument of length 0
> Stack trace (innermost first):
>     106: <Anonymous>
>     105: stop
>     104: planneddf
>     103: list_or_dots
>     102: dplyr::bind_cols
>     101: eval
>     100: eval
>      99: %>%
>      98: <reactive:df_plots> [C:\Users\Christopher\Documents\CA_Data_Collab\repos\RateComparison/server.R#296]
>      87: df_plots
>      86: eval
>      85: eval
>      84: %>%
>      83: is.data.frame
>      82: colSums
>      81: plot_fixed_revenue [R/make_plots.R#245]
>      80: inherits [C:\Users\Christopher\Documents\CA_Data_Collab\repos\RateComparison/server.R#742]
>      79: as.widget
>      78: func
>      77: origRenderFunc
>      76: output$fixed_revenue_barchart
>       1: shiny::runApp
> Warning: Error in :: argument of length 0
> Stack trace (innermost first):
>     87: <Anonymous>
>     86: stop
>     85: df_plots
>     84: eval
>     83: eval
>     82: %>%
>     81: plot_revenue_over_time [R/make_plots.R#21]
>     80: inherits [C:\Users\Christopher\Documents\CA_Data_Collab\repos\RateComparison/server.R#430]
>     79: as.widget
>     78: func
>     77: origRenderFunc
>     76: output$revenue_time_series
>      1: shiny::runApp
> Warning: Error in :: argument of length 0
> Stack trace (innermost first):
>     89: <Anonymous>
>     88: stop
>     87: df_plots
>     86: eval
>     85: eval
>     84: %>%
>     83: is.data.frame
>     82: colSums
>     81: plot_barchart_by_tiers [R/make_plots.R#199]
>     80: inherits [C:\Users\Christopher\Documents\CA_Data_Collab\repos\RateComparison/server.R#500]
>     79: as.widget
>     78: func
>     77: origRenderFunc
>     76: output$barchart_by_tiers
>      1: shiny::runApp
> Warning: Error in :: argument of length 0
> Stack trace (innermost first):
>     99: <Anonymous>
>     98: stop
>     97: df_plots
>     96: eval
>     95: eval
>     94: %>%
>     93: <reactive:df_change> [C:\Users\Christopher\Documents\CA_Data_Collab\repos\RateComparison/server.R#523]
>     82: df_change
>     81: plot_bill_change_histogram [R/make_plots.R#102]
>     80: inherits [C:\Users\Christopher\Documents\CA_Data_Collab\repos\RateComparison/server.R#703]
>     79: as.widget
>     78: func
>     77: origRenderFunc
>     76: output$bill_change_histogram
>      1: shiny::runApp

> Warning: Error in :: argument of length 0
> Stack trace (innermost first):
>     84: <Anonymous>
>     83: stop
>     82: df_change
>     81: plot_bill_change_boxplot [R/make_plots.R#153]
>     80: inherits [C:\Users\Christopher\Documents\CA_Data_Collab\repos\RateComparison/server.R#723]
>     79: as.widget
>     78: func
>     77: origRenderFunc
>     76: output$bill_change_boxplot
>      1: shiny::runApp
> ERROR: [on_request_read] connection reset by peer

**Comment by christophertull** [comment]
Can we close this?

**Comment by anudeepvanjavakam1** [comment]
Yes, it is fixed. Please close it.
