### ISSUE TITLE
Enabling planning changes revenue calcs

### ISSUE THREAD

**Issue by christophertull** [California-Data-Collaborative/RateComparison#30]
When on budget based rates, enabling planning changes the revenue calcs from this:

![image](https://cloud.githubusercontent.com/assets/9061565/21239742/1146d614-c2bd-11e6-8e89-69d5c22335e6.png)

to this:

![image](https://cloud.githubusercontent.com/assets/9061565/21239752/207859dc-c2bd-11e6-942e-f8e0a1d7757c.png)

**Comment by christophertull** [comment]
This seems to be gone, so I am closing.

**Comment by patwater** [comment]
What was causing this out of curiosity?

**Comment by patwater** [comment]
![image](https://cloud.githubusercontent.com/assets/1587811/22172785/397220e8-df65-11e6-8d04-58d222f8060d.png)
