### ISSUE TITLE
Hypothetical revenue bar does not appear under flat rate

### ISSUE THREAD

**Issue by christophertull** [California-Data-Collaborative/RateComparison#36]
See barchart.
![image](https://cloud.githubusercontent.com/assets/9061565/21626709/89bb8068-d1c7-11e6-969c-7f3338fb8133.png)

**Comment by patwater** [comment]
Weird.  @christophertull theories on origin of it?

**Comment by christophertull** [comment]
Not sure. Haven't gone digging yet. Smells like a small one line fix though.

**Comment by christophertull** [comment]
@anudeepvanjavakam1 Feel free to close if everything seems to be working.

**Comment by anudeepvanjavakam1** [comment]
It is fixed!
