### ISSUE TITLE
MNWD Rate Codes Misaligned

### ISSUE THREAD

**Issue by datwater** [California-Data-Collaborative/RateComparison#40]
MNWD rate codes issues:
RW does not include RC5 (RC 5 is hydrant and should be in OTHER- they don't have a budget)
RESIDENTIAL_MULTI should have A2 included (its not in any others from what I could see (note that A2 does not have sewer for the sewer model)
COMMERCIAL should not include CM1MN or CM2MN as those are MNWD accounts and do not pay bills- delete from Commercial- could be in INSTITUTIONAL if desired to include

**Comment by christophertull** [comment]
Thanks for the heads up!

**Comment by patwater** [comment]
@christophertull is this the genesis of the rate specific customer classification you were thinking of?

**Comment by christophertull** [comment]
Part of it. The other part is that many utilities have classes like "RECYCLED" or "RECREATIONAL" that don't cleanly fit into our current schema

**Comment by patwater** [comment]
Oh gotcha.  The cust_loc_class really is aligned with the DWR statewide customer water use classes so thought is there would also be a general local utility rate class in addition to the granular rate code, yeah?

**Comment by christophertull** [comment]
Exactly. Idea would be:

* `cust_loc_class` = conceptual class aligned with DWR
* `cust_loc_class_from_utility` = rate code = finest grained customer classification available from utilities
* `cust_loc_rate_class` = grouping of rate codes classes that are billed similarly for purposes of OWRS/RateComparison

**Comment by christophertull** [comment]
Closed by #44

**Comment by patwater** [comment]
Does this need to update the SCUBA schema so it explicitly includes cust_loc_rate_class? https://github.com/California-Data-Collaborative/scuba-docs

**Comment by christophertull** [comment]
Yes!
