### ISSUE TITLE
Account for predicted population growth

### ISSUE THREAD

**Issue by christophertull** [California-Data-Collaborative/RateComparison#6]
Users should be able to specify a growth rate, (e.g. 1% per year, 200 accounts per year, etc) and that growth rate should get factored into water demand forecasts. This should be implemented in the scenario planning tab ( issue #5 ).
### Implementation

One thought would be to randomly sample from existing customers in order to simulate growth in the future. 

If random sampling is chosen, then care should be taken that the the sample is done proportionate to the expected growth in each customer class. (e.g. if only residential growth is expected, then we shouldn't be sampling from industrial)

**Comment by christophertull** [comment]
@anudeepvanjavakam1 Do you think you could talk to Drew and get his thoughts on the implementation of this issue and #7 ? Might be easier to explain the methodology in person and show him a demo (is he back in town yet?).  Otherwise we can shoot him an email. Thoughts?

**Comment by anudeepvanjavakam1** [comment]
@christophertull yeah sure. I can explain the methodology tomorrow and see what Drew thinks about it.

**Comment by christophertull** [comment]
Sounds great, thanks.

**Comment by patwater** [comment]
@anudeepvanjavakam1 any thoughts from drew?

**Comment by anudeepvanjavakam1** [comment]
@patwater I have shown the scenario planning and briefly gave its overview to Drew. He was appreciative and said he needs some time to gather his thoughts before suggesting any improvements/changes.

**Comment by patwater** [comment]
Cool sounds good.  Please relay when available

**Comment by christophertull** [comment]
Closed by #41
