### ISSUE TITLE
Forecast water use into the future

### ISSUE THREAD

**Issue by christophertull** [California-Data-Collaborative/RateComparison#7]
If scenario planning is enabled ( see issue #5 ), then instead of just looking retroactively, we should be able to forecast water use into the future.

The exact details are completely open, but some possibilities include:
1. Extrapolating past use into the future, either by copying directly or by averaging over previous years.
2. Creating a statistical model of water demand in aggregate for each customer class (care should be taken here so that factors like population growth can be factored in).
3. Creating a statistical model at the customer level and then aggregating up to each customer class. This would be the most complicated but also the most flexible.

Option 1 would probably be a good and relatively easy start, with option 3 probably being the best choice overall.

**Comment by christophertull** [comment]
Hey @anudeepvanjavakam1 , can we call this on closed for now? Will leave #6 open since you are still tweaking it.

**Comment by anudeepvanjavakam1** [comment]
@christophertull Yes, this is resolved. We can close this.
